### ISSUE TITLE
Multinational Keyboard Support

### ISSUE THREAD

**Issue by spacesvr** [spacesvr/spacesvr#32]
There should be as little friction as possible on the end user, so auto-detecting keyboard layout would be ideal

**Comment by alex-shortt** [comment]
this might be the answer: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

**Comment by AlaricBaraou** [comment]
Just tried this example http://output.jsbin.com/noyudo/5
From this article https://hacks.mozilla.org/2017/03/internationalize-your-keyboard-controls/

The main issue remains, for most case we can't detect the layout.

We could update the WASD/ZQSD/... indicator when the user press whatever key that correspond to code='KeyW' 

There is also this experimental Keyboard API that could allow us to detect the Keyboard layout in some browsers.
https://developer.mozilla.org/en-US/docs/Web/API/Keyboard_API

```
if (navigator.keyboard) {
  var keyboard = navigator.keyboard;
  keyboard.getLayoutMap()
  .then(keyboardLayoutMap => {
    var upKey = keyboardLayoutMap.get('KeyW');
    window.alert('Press ' + upKey + ' to move up.');
  });
} else {
  // Do something else.
}
```

**Comment by alex-shortt** [comment]
found this, seems like event.code is the right way?

https://github.com/mozilla/hubs/issues/2397

you probably can't explicitly detect which keyboard the user is using but just look for the keys in the right position at the very least
