### ISSUE TITLE
FacePlayer type is invalid

### ISSUE THREAD

**Issue by jonrrivera** [spacesvr/spacesvr#74]
<img width="1072" alt="Screen Shot 2022-03-09 at 10 28 35 PM" src="https://user-images.githubusercontent.com/18686388/157602509-cc0da46a-12e9-4201-9421-735059292381.png">

what would be the best to import the `FacePlayer` component? I am getting this error when importing as a named export

**Comment by alex-shortt** [comment]
can i see your code trying to import and use FacePlayer? also i know you mentioned that you had some invalid dependencies, once fixed is it working?

**Comment by jonrrivera** [comment]
it was just a normal import 
`import { Interactable, FacePlayer, Spinning, Tool, Floating, Fog, Background, StandardEnvironment, Audio, Arrow, Text } from "spacesvr";`

but now seems like its fixed on latest spacevr `1.9.1` :)
