### ISSUE TITLE
Fail to load texture

### ISSUE THREAD

**Issue by jonrrivera** [spacesvr/spacesvr#81]
Been trying extensively to load a texture into a (ground type) model, but continue to get this error. 

I am able to see the render on a latest three js version environment, but for some reason I continue to get this error within spacevr

<img width="537" alt="Screen Shot 2022-03-30 at 12 12 55 PM" src="https://user-images.githubusercontent.com/18686388/160912857-6a9eddc0-71a7-4532-878b-6a513aa36857.png">

would really appreciate any help!!

**Comment by alex-shortt** [comment]
can i see the code?

**Comment by alex-shortt** [comment]
pretty sure this is unrelated to spacesvr, or if it is then probably due to to #84 ... i saw you fixed it recently so lmk if i'm wrong, but closing for now
