### ISSUE TITLE
no Drei Components not working inside StandardEnvironment

### ISSUE THREAD

**Issue by jonrrivera** [spacesvr/spacesvr#82]
Hey!

Been looking for ways to better present my component, but I can't seem to render any Drei `7.0.6` component inside the spacevr StandardEnvironment. This is the error I get:

<img width="1287" alt="Screen Shot 2022-04-14 at 8 48 56 AM" src="https://user-images.githubusercontent.com/18686388/163426673-94cf89f0-c91c-4e7d-9d73-ac3e97e530f9.png">

Happy any code or environment if needed, but you should be able to recreate using the spacevr next js starter with:

`
    "three": "^0.127.0",
    "spacesvr": "latest",
    "react": "^17.0.2",
    "@react-spring/web": "^9.2.1",
    "@react-three/cannon": "^4.9.0",
    "@react-three/drei": "7.0.6",
    "@react-three/fiber": "6.0.14",
`

**Comment by alex-shortt** [comment]
hey like we went over, pretty much all due to #84. There's a lot of intricate package pinning you need to do until that's fixed. hopefully you got it to work though!
